# Generated by Django 4.0.5 on 2022-06-16 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barsa_app', '0003_contract_name_alter_employee_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gamecalendar',
            name='coach',
        ),
        migrations.AddField(
            model_name='gamecalendar',
            name='coach',
            field=models.ManyToManyField(to='barsa_app.coach'),
        ),
        migrations.RemoveField(
            model_name='gamecalendar',
            name='footballer',
        ),
        migrations.AddField(
            model_name='gamecalendar',
            name='footballer',
            field=models.ManyToManyField(to='barsa_app.footballers'),
        ),
    ]
