# Generated by Django 4.0.5 on 2022-06-27 08:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('barsa_app', '0006_remove_gamecalendar_date_time_gamecalendar_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tickets',
            name='game',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='barsa_app.gamecalendar'),
        ),
    ]
